In [2]:
import pandas as pd

In [5]:
data = {'mother': [63, 67, 64, 60, 65, 67, 59, 60, 58, 72, 63, 67, 62, 69, 63, 64, 63, 64, 60, 65],
        'father': [64, 65, 67, 72, 72, 72, 67, 71, 66, 75, 69, 70, 69, 62, 66, 76, 69, 68, 66, 68],
        'daughter': [58.6, 64.7, 65.3, 61, 65.4, 67.4, 69.9, 63.1, 60, 71.1, 62.2, 67.2, 63.4, 68.4, 62.2, 64.7, 59.6, 61, 64, 65.4]
        }
df = pd.DataFrame(data,columns=['mother','father','daughter'])
df

    mother  father  daughter
0       63      64      58.6
1       67      65      64.7
2       64      67      65.3
3       60      72      61.0
4       65      72      65.4
5       67      72      67.4
6       59      67      69.9
7       60      71      63.1
8       58      66      60.0
9       72      75      71.1
10      63      69      62.2
11      67      70      67.2
12      62      69      63.4
13      69      62      68.4
14      63      66      62.2
15      64      76      64.7
16      63      69      59.6
17      64      68      61.0
18      60      66      64.0
19      65      68      65.4